server.port=8084
spring.application.name=responder-service

spring.datasource.url=jdbc:mysql://localhost:3306/responder_db
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ? Disable Eureka server dependency (no server needed)
eureka.client.enabled=false
spring.cloud.discovery.enabled=false

# ? Optional: disable Feign discovery (so Feign doesn't try Eureka)
spring.cloud.openfeign.enabled=true
spring.cloud.loadbalancer.enabled=false